// app/layout.tsx or app/layout.jsx
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./comps/ui/sideBar";
import NavBar from "./comps/ui/navBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white min-h-screen flex`}
      >
        {/* Sidebar */}
        <SideBar className="w-64 bg-zinc-900 p-4" />

        {/* Main Content */}
        <main className="flex flex-col w-full">
          <NavBar />
          <div className="p-6">{children}</div>
        </main>
      </body>
    </html>
  );
}
